
name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - run: npm install
      - run: npm run build

      # https://github.com/amondnet/vercel-action/blob/f79b066724a2ac14b8944244a625146e5d6006c3/.github/workflows/example-static.yml
      - name: production or not
        id: prod_or_not
        run: |
          if [ "$REF" == 'refs/heads/master' ]
          then
              echo "::set-output name=vercel-args::--prod"
          else
              echo "::set-output name=vercel-args::"
          fi
        env:
          REF: ${{ github.ref }}

      - uses: amondnet/vercel-action@v19
        with:
          # github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          alias-domains: |
            {{BRANCH}}.vercel.facemorph.me
          vercel-args: ${{ steps.prod_or_not.outputs.vercel-args }}